

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minha_base
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
