services:
  db:
    image: mysql
    container_name: mysql_server
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
